In [8]:
import os 
import datetime
from pathlib import Path
from dotenv import load_dotenv, find_dotenv

basepath = Path(os.getcwd())
# make sure your working directory is the repository root.
if basepath.name != "idp-radio-1":
    os.chdir(basepath.parent.parent)
load_dotenv(find_dotenv())

%load_ext autoreload
%autoreload 2
os.getcwd()

The autoreload extension is already loaded. To reload it, use:
  %reload_ext autoreload


'C:\\Users\\tsbau\\git\\idp-radio-1'

In [23]:
import tensorflow as tf
import tensorflow.keras as keras
import pandas as pd
import numpy as np
from skimage.transform import resize
from sklearn.metrics import classification_report
from sklearn.model_selection import train_test_split
from keras_preprocessing.image import ImageDataGenerator
from tensorflow.keras.models import Model, load_model
from tensorflow.keras.layers import Dense, GlobalAveragePooling2D
from tensorflow.keras.applications import resnet_v2
from tensorflow.keras.callbacks import TensorBoard
from src.utils.save_model import save_model, model_set
#from src.datasets.generator import ImageDataGenerator

In [32]:
test = np.array([[0,1,-1], [0,-1,0]])
test 

array([[ 0,  1, -1],
       [ 0, -1,  0]])

In [33]:
mask = test == -1
mask

array([[False, False,  True],
       [False,  True, False]])

In [38]:
test[mask] = 2
test

array([[0, 1, 2],
       [0, 2, 0]])

In [54]:
from tensorflow.keras.utils import to_categorical
encoded  = to_categorical(test)
encoded

array([[[1., 0., 0.],
        [0., 1., 0.],
        [0., 0., 1.]],

       [[1., 0., 0.],
        [0., 0., 1.],
        [1., 0., 0.]]], dtype=float32)

In [46]:
np.prod(encoded.shape[1:])

9

array([[1., 0., 0., 0., 1., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 1., 1., 0., 0.]], dtype=float32)

In [52]:
newshape = encoded.shape[:1] + (np.prod(encoded.shape[1:]),)
newshape

(2, 9)

In [53]:
encoded.reshape(newshape)

array([[1., 0., 0., 0., 1., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 1., 1., 0., 0.]], dtype=float32)